# Generated by Django 6.0.2 on 2026-02-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=32)),
                ('course_title', models.CharField(blank=True, max_length=128)),
                ('lecturer_name', models.CharField(max_length=128)),
                ('room', models.CharField(blank=True, max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('token_version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64)),
                ('device_id', models.CharField(max_length=128)),
                ('acoustic_token', models.CharField(max_length=128)),
                ('ble_nonce', models.CharField(max_length=128)),
                ('rssi', models.IntegerField()),
                ('observed_at', models.DateTimeField()),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='attendance.session')),
            ],
            options={
                'unique_together': {('session', 'student_id')},
            },
        ),
    ]
