# Generated by Django 6.0.2 on 2026-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
