# Generated by Django 6.0.2 on 2026-02-17 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_session_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReplayGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_token', models.CharField(max_length=128)),
                ('ble_nonce', models.CharField(max_length=128)),
                ('student_id', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_guards', to='attendance.session')),
            ],
            options={
                'unique_together': {('session', 'challenge_token', 'ble_nonce')},
            },
        ),
    ]
